apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: myapp
  namespace: flux-system
spec:
  interval: 1m
  path: ./app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
