apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: final
  labels:
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: [ecr/repo]  # {"$imagepolicy": "flux-system:myapp"}
        ports:
        - containerPort: 81
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
          - name: DBHOST
            valueFrom:
              configMapKeyRef:
                name: app-config  # Name of the ConfigMap
                key: DBHOST
          - name: DBPORT
            valueFrom:
              configMapKeyRef:
                name: app-config  # Name of the ConfigMap
                key: DBPORT
          - name: DATABASE
            valueFrom:
              configMapKeyRef:
                name: app-config  # Name of the ConfigMap
                key: DATABASE 
          - name: APP_NAMES
            valueFrom:
              configMapKeyRef:
                name: app-config  # Name of the ConfigMap
                key: APP_NAMES  
          - name: APP_IMG
            valueFrom:
              configMapKeyRef:
                name: app-config  # Name of the ConfigMap
                key: APP_IMG
          - name: APP_PORT
            valueFrom:
              configMapKeyRef:
                name: app-config  # Name of the ConfigMap
                key: APP_PORT
          - name: AWS_DEFAULT_REGION
            valueFrom:
              configMapKeyRef:
                name: app-config  # Name of the ConfigMap
                key: AWS_DEFAULT_REGION
          - name: DBPWD
            valueFrom:
              secretKeyRef:
                name: app-secrets  # Name of the Secret
                key: DBPWD
          - name: DBUSER
            valueFrom:
              secretKeyRef:
                name: app-secrets  # Name of the Secret
                key: DBUSER
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: app-secrets  # Name of the Secret
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets  # Name of the Secret
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_SESSION_TOKEN
            valueFrom:
              secretKeyRef:
                name: app-secrets  # Name of the Secret
                key: AWS_SESSION_TOKEN
      imagePullSecrets:
        - name: ecr-secret 
